---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/stack --version
      register: haskell_stack_test_output
    - name: stack --version
      debug:
        msg: '{{ haskell_stack_test_output.stdout }}'
    - name: setup...
      command: /usr/local/bin/stack setup
      args:
        creates: '{{ ansible_env.HOME }}/.stack'
