---
- name: Testing andrewrothstein.haskell
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'stack --version'
      ansible.builtin.command: stack --version
      changed_when: false
      register: haskell_stack_test_output
    - name: Output from 'stack --version'
      ansible.builtin.debug:
        msg: '{{ haskell_stack_test_output.stdout }}'
    - name: Setting up...
      command: stack setup
      args:
        creates: '{{ ansible_env.HOME }}/.stack'
