---
- name: (Debian) install haskell
  when: ansible_os_family == 'Debian'
  apt: name={{ item }} state=latest
  with_items:
    - haskell-platform

- name: (RedHat) install haskell
  when: ansible_os_family == "RedHat"
  yum: name={{ item }} state=latest
  with_items:
    - haskell-platform
