---
- name: andrewrothstein.unarchivedeps
  version: 3.0.3
- name: andrewrothstein.gcc_toolbox
  version: 2.0.5
- name: andrewrothstein.git
  version: v3.2.11
- name: andrewrothstein.gpg
  version: v1.2.5
- name: andrewrothstein.bash
  version: v1.2.2
