---
- role: andrewrothstein.unarchive-deps
  version: v1.2.3
- role: andrewrothstein.gcc-toolbox
  version: v1.1.5
- role: andrewrothstein.git
  version: v3.1.6
- role: andrewrothstein.gpg
  version: v1.0.11
- role: andrewrothstein.bash
  version: v1.1.10
